title: Kevin Rosario's Portfolio

plugins:
  - jekyll-bookshop
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-toc
  # - jekyll-target-blank

# Multiple bookshops can be used on one website,
# or different production / staging locations.
bookshop_locations:
  - ./component-library

exclude:
  - postcss.config.js
  - node_modules

collections_dir: 'collections'

collections:
  pages:
    output: true
    permalink: /:title/
  projects:
    output: false
    permalink: /blog/:slug
  testimonials:
    output: false
  posts:
    output: true
    permalink: /project/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: pages
      path: _pages/index.html
    values:
      permalink: /
  - scope:
      type: projects
    values:
      layout: project
  - scope:
      type: posts
    values:
      layout: post

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: /:title

stats:
  category_stats:
    - name: Launches
      count: 18
      color: "#b083f0"
    - name: Migrations
      count: 30
      color: "#60a6ff"
    - name: Divestitures
      count: 68
      color: "#ff9bbf"
    - name: Clients
      count: 28+
      color: "#4de3b0"

  # creation_stats:
  #   - name: Articles
  #     count: 70
  #   - name: Book Notes
  #     count: 16
  #   - name: Digital Products
  #     count: 9
  #   - name: GitHub Repos
  #     count: 2
  #   - name: Newsletter Editions
  #     count: 44
  #   - name: Websites
  #     count: 3