title: Kevin Rosario's Portfolio
description: Kevin Rosario's Portfolio using a portfolio site template for Jekyll
social_media_share_image: /images/kevin-profile.jpg
disqus-identifier:
google-analytics: