# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Projects
  description: Projects Section with heading, a description and a link
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  title: ""
  description_html: ""
  link_url: ""
  show_projects: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: All my projects
  description_html: Each project is associated to a city or landmark I've come across on my travels, but since you already know that check out the rest of my projects!
  link_url: /projects

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
